import React from 'react';
import Header from '../components/Header';

export default function About() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-16">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-4">
            Welcome to HealthifyMe – Your Smart Health Companion 💙
          </h1>
          <p className="text-base md:text-lg text-foreground mb-6">
            We help users understand their symptoms quickly with AI-powered health analysis, simple explanations, and safe precautions.
          </p>
          <p className="text-base md:text-lg text-muted-foreground mb-12">
            Our mission is to make health awareness easy, fast, and accessible for everyone.
          </p>

          <div className="bg-card p-6 sm:p-8 rounded-xl shadow-md border border-border">
            <h2 className="text-2xl md:text-3xl font-bold text-primary mb-6">👨‍💻 Creators</h2>
            <p className="text-muted-foreground mb-6">Developed with passion by:</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-base md:text-lg font-semibold text-primary">
              <a 
                href="https://www.linkedin.com/in/sumitchaudhari07?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" 
                target="_blank" 
                rel="noopener noreferrer" 
                className="p-4 rounded-lg border border-primary/20 bg-primary/5 hover:bg-primary/10 hover:underline transition-all"
              >
                Sumit Chaudhari
              </a>
              <a 
                href="https://www.linkedin.com/in/rohan-gupta-723191272?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" 
                target="_blank" 
                rel="noopener noreferrer" 
                className="p-4 rounded-lg border border-primary/20 bg-primary/5 hover:bg-primary/10 hover:underline transition-all"
              >
                Rohan Gupta
              </a>
              <a 
                href="https://www.linkedin.com/in/shreyanshshekhar17?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" 
                target="_blank" 
                rel="noopener noreferrer" 
                className="p-4 rounded-lg border border-primary/20 bg-primary/5 hover:bg-primary/10 hover:underline transition-all"
              >
                Shreyansh Shekhar
              </a>
            </div>
            <p className="mt-8 text-foreground text-sm md:text-base">
              Together, we are building technology that supports people in living a healthier and safer life.
            </p>
          </div>
        </div>
      </main>
      <footer className="bg-accent h-36 w-full flex items-center justify-center p-4">
        <p className="text-black text-center text-xs sm:text-sm max-w-2xl font-medium leading-relaxed">
          This health result is generated by an AI-based symptom checker and is NOT a medical diagnosis.
          Information provided is for educational and awareness purposes only.
        </p>
      </footer>
    </div>
  );
}
